### ISSUE TITLE
go get suddenly failing with 404s

### ISSUE THREAD

**Issue by kari-malachi** [databricks/databricks-sdk-go#300] opened 2023-02-14 00:03 UTC
The errors are somewhat inconsistent upon retries. But here are some examples:

```
go get -x -v github.com/databricks/databricks-sdk-go@v0.3.0
# get https://proxy.golang.org/github.com/@v/v0.3.0.info
# get https://proxy.golang.org/github.com/databricks/@v/v0.3.0.info
# get https://proxy.golang.org/github.com/@v/v0.3.0.info: 404 Not Found (0.376s)
# get https://proxy.golang.org/github.com/databricks/@v/v0.3.0.info: 404 Not Found (0.380s)
panic: internal error: can't find reason for requirement on github.com/golang/snappy@v0.0.1
```

```
go get -x -v 
...
# get https://proxy.golang.org/github.com/@v/list
# get https://proxy.golang.org/github.com/databricks/databricks-sdk-go/service/@v/list
# get https://proxy.golang.org/github.com/databricks/@v/list
# get https://proxy.golang.org/github.com/databricks/databricks-sdk-go/service/permissions/@v/list
# get https://proxy.golang.org/github.com/databricks/databricks-sdk-go/service/clusterpolicies/@v/list
# get https://proxy.golang.org/github.com/databricks/databricks-sdk-go/config/@v/list
# get https://proxy.golang.org/github.com/@v/list: 404 Not Found (0.008s)
# get https://proxy.golang.org/github.com/databricks/@v/list: 404 Not Found (0.253s)
...

```
Thank you for any help! This is on go version go1.19.4 and also tried it on 1.18.10 with similar errors

**Comment by nfx** [comment] 2023-02-16 11:37
@kari-malachi is it still the case?... we cannot reproduce it...

**Comment by pietern** [comment] 2023-09-15 10:04
This hasn't come up again. Closing the issue.

**Closed by pietern** 2023-09-15 10:04 UTC
